a=float(input('Digite a primeira nota: '))
b=float(input('Digite a segunda nota: '))
m=((a+b)/2)
print('As notas do aluno foram {} e {} e sua média nesse bimestre é {}'.format(a,b,m))


t=int(input('Digite um número para ver sua tabuada: '))
a=(t*1)
b=(t*2)
c=(t*3)
d=(t*4)
e=(t*5)
f=(t*6)
g=(t*7)
h=(t*8)
i=(t*9)
j=(t*10)
print('-'*13)
print('{} X 1 = {}'.format(t,a))
print('{} X 2 = {}'.format(t,b))
print('{} X 3 = {}'.format(t,c))
print('{} X 4 = {}'.format(t,d))
print('{} X 5 = {}'.format(t,e))
print('{} X 6 = {}'.format(t,f))
print('{} X 7 = {}'.format(t,g))
print('{} X 8 = {}'.format(t,h))
print('{} X 9 = {}'.format(t,i))
print('{} X 10 = {}'.format(t,j))
print('-'*13)