alimento=('hamburguer','suco','pizza','café','pão','cenoura')
for comida in alimento:
    print(f'Eu gosto de {comida}')
print(alimento[1])
print(alimento[-2])
print(alimento[1:3])
print(alimento[0])
print(alimento[0:])
print(alimento[:-2])
print(alimento[-2:])
print(sorted(alimento))